apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: single-nodejs-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: single-nodejs-app
    app.kubernetes.io/part-of: single-nodejs-app
  name: single-nodejs-app
  namespace: user1-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: single-nodejs-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: single-nodejs-app
    spec:
      containers:
      - image: quay.io/jduimovich0/single-nodejs-app@sha256:4a6ff49f9d041c0ac177e79cff8a0e107027ad8bbb3c773342fce4cfff407003
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 512Mi
status: {}
